version: '3'

services:
  serveur:
    build:
      context: .        # racine du serveur
    ports:
      - "5000:5000"
    depends_on:
      - api
    networks:
      - network_rt0704
    volumes:
      - ./:/app           # monte le dossier courant vers /app dans le conteneur

  api:
    build:
      context: ./api
    ports:
      - "5001:5000"       # l'API écoute sur 5000 dans le conteneur mais exposée sur 5001
    networks:
      - network_rt0704
    volumes:
      - ./api:/app

networks:
  network_rt0704:
    driver: bridge
